// subcategories: fundamentals, navigation-and-linking, document-architecture, visual-content-and-media, intro-into-web-development, organization-and-structure
export default [
    {
        id: 1,
        type: 'radio',
        category: 'html',
        subcategory: 'navigation-and-linking',
        title: 'target=\"_?\"',
        question: "Which of the following \`target\` attributes opens a link in the parent of the current context?",
        options: [
            '\`_self\`',
            '\`_unfencedTop\`',
            '\`_parent\`',
            '\`_blank\`'
        ],
        random: true,
        answer: '\`_parent\`',
    },
    {
        id: 2,
        type: 'radio',
        category: 'html',
        subcategory: 'document-architecture',
        title: 'UTF attribute?',
        question: "Which attribute is used to set the \`UTF-8\` character encoding for an HTML document?",
        options: [
            '\`charset\`',
            '\`enctype\`',
            '\`capture\`',
            '\`accept\`',
            '\`pattern\`',
            '\`content\`',
            '\`lang\`',
            '\`encode\`'
        ],
        random: true,
        answer: '\`charset\`',
    },
    {
        id: 3,
        type: 'radio',
        category: 'html',
        subcategory: 'fundamentals',
        title: 'Why HTML',
        question: "What is the role of HTML on the web?",
        options: [
            'HTML represents the content and structure for a web page',
            'HTML is used for style and layout',
            'HTML is used to add interactivity on the page',
            'HTML is a registry for software packages'
        ],
        random: true,
        answer: 'HTML represents the content and structure for a web page',
    },
    {
        id: 4,
        type: 'radio',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'Licensed to image',
        question: "Which image license works for the public domain?",
        options: [
            'JPG',
            'Creative Commons',
            'BSD',
            'Creative Commons 0'
        ],
        random: true,
        answer: 'Creative Commons 0',
    },
    {
        id: 5,
        type: 'radio',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'How to false',
        question: "How do you set a boolean attribute to \`false\`?",
        options: [
            'By using the \`not\` operator before the attribute name',
            'By omitting the attribute from the element',
            'By setting the attribute value to \`0\`',
            'By setting the attribute to an empty string (\`""\`)'
        ],
        random: true,
        answer: 'By omitting the attribute from the element',
    },
    {
        id: 6,
        type: 'radio',
        category: 'html',
        subcategory: 'intro-into-web-development',
        title: 'Why script',
        question: "What is the \`script\` element used for?",
        options: [
            'It is used to embed Pascal code into the HTML document',
            'It is used to embed C# code into the HTML document',
            'It is used to embed JavaScript into the HTML document or link to an external JavaScript file',
            'It is used to embed CSS into the HTML document or link to an external CSS file'
        ],
        random: true,
        answer: 'It is used to embed JavaScript into the HTML document or link to an external JavaScript file',
    },
    {
        id: 7,
        type: 'radio',
        category: 'html',
        subcategory: 'document-architecture',
        title: 'HTML title',
        question: "Which of the following elements is used to set the title for an HTML document?",
        options: [
            '\`title\`',
            '\`footer\`',
            '\`figcaption\`',
            '\`section\`'
        ],
        random: true,
        answer: '\`title\`',
    },
    {
        id: 8,
        type: 'radio',
        category: 'html',
        subcategory: 'organization-and-structure',
        title: 'All class',
        question: "What is the \`class\` attribute typically used for?",
        options: [
            'to define inline styles directly within the HTML tag',
            'to specify unique identifiers for JavaScript functions',
            'to embed metadata about the element',
            'to apply a set of styles to multiple elements'
        ],
        random: true,
        answer: 'to apply a set of styles to multiple elements',
    },
    {
        id: 9,
        type: 'radio',
        category: 'html',
        subcategory: 'navigation-and-linking',
        title: 'Relative to who',
        question: "What is a relative path?",
        options: [
            'it specifies the exact location of a file or directory from the root directory of the file system',
            'it always begins with a forward slash (\`/\`) indicating the root directory of the website or file system',
            'it specifies the location of a file or directory relative to the current working directory',
            'it includes the full URL starting from the domain name to the specific file or directory'
        ],
        random: true,
        answer: 'it specifies the location of a file or directory relative to the current working directory',
    },
    {
        id: 10,
        type: 'radio',
        category: 'html',
        subcategory: 'navigation-and-linking',
        title: 'Link syntax',
        question: "Which of the following elements is the correct syntax for a \`link\` element?",
        options: [
            '\`<link rel="stylesheet" href="./styles.css"></link>\`',
            '\`<link rel="stylesheet" href="./styles.css" />\`',
            'None of the above'
        ],
        random: false,
        answer: '\`<link rel="stylesheet" href="./styles.css" />\`',
    },
    {
        id: 11,
        type: 'radio',
        category: 'html',
        subcategory: 'intro-into-web-development',
        title: 'No can do bucaroo',
        question: "Which of the following is NOT a valid value for working with open graph properties?",
        options: [
            '\`"og:image"\`',
            '\`"og:type"\`',
            '\`"og:socialMedia"\`',
            '\`"og:title"\`'
        ],
        random: true,
        answer: '\`"og:socialMedia"\`',
    },
    {
        id: 12,
        type: 'radio',
        category: 'html',
        subcategory: 'fundamentals',
        title: 'Hey that might leak',
        question: "What does HTML stand for?",
        options: [
            'HyperText Maker Language',
            'HyperText Marker Language',
            'HyperText Markdown Language',
            'HyperText Markup Language'
        ],
        random: true,
        answer: 'HyperText Markup Language',
    },
    {
        id: 13,
        type: 'radio',
        category: 'html',
        subcategory: 'fundamentals',
        title: 'How to close',
        question: "Which of the following is the correct syntax for a closing tag?",
        options: [
            '\`<p>\`',
            '\`<;p>\`',
            '\`</p>\`',
            '\`<\\p>\`'
        ],
        random: true,
        answer: '\`</p>\`',
    },
    {
        id: 14,
        type: 'checkbox',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'Valid for img',
        question: "Which of the following are valid attributes used inside the \`img\` element?",
        options: [
            '\`src\`',
            '\`bold\`',
            '\`closing\`',
            '\`div\`',
            '\`alt\`',
            '\`pic\`',
            '\`from\`',
            '\`file\`'
        ],
        random: true,
        answer: ['\`src\`', '\`alt\`'],
    },
    {
        id: 15,
        type: 'radio',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'Boo who',
        question: "Which of the following is an example of a boolean attribute?",
        options: [
            '\`text\`',
            '\`email\`',
            '\`src\`',
            '\`disabled\`'
        ],
        random: true,
        answer: '\`disabled\`',
    },
    {
        id: 16,
        type: 'radio',
        category: 'html',
        subcategory: 'document-architecture',
        title: 'Where do we encode?',
        question: "Where would you set the character encoding for your page?",
        options: [
            '\`meta\` element in the \`body\`',
            '\`head\` element in the \`body\`',
            '\`meta\` element in the \`head\`',
            'in the \`DOCTYPE\`'
        ],
        random: true,
        answer: '\`meta\` element in the \`head\`',
    },
    {
        id: 17,
        type: 'radio',
        category: 'html',
        subcategory: 'document-architecture',
        title: 'Char encoding',
        question: "What is character encoding?",
        options: [
            'a method computers use to store characters as data',
            'a way to compress files',
            'determines the font used to display text on a screen',
            'refers to the process of converting spoken language into written text'
        ],
        random: true,
        answer: 'a method computers use to store characters as data',
    },
    {
        id: 18,
        type: 'radio',
        category: 'html',
        subcategory: 'organization-and-structure',
        title: 'Fake id',
        question: "Which of the following is NOT a correct value for the \`id\` attribute?",
        options: [
            '\`id="main"\`',
            '\`id="div"\`',
            '\`id="main-div"\`',
            '\`id="main div"\`'
        ],
        random: true,
        answer: '\`id="main div"\`',
    },
    {
        id: 19,
        type: 'radio',
        category: 'html',
        subcategory: 'intro-into-web-development',
        title: 'Link to JS',
        question: "Which attribute is used to link to an external JavaScript file?",
        options: [
            'the \`div\` attribute',
            'the \`defer\` attribute',
            'the \`async\` attribute',
            'the \`src\` attribute'
        ],
        random: true,
        answer: 'the \`src\` attribute',
    },
    {
        id: 20,
        type: 'radio',
        category: 'html',
        subcategory: 'intro-into-web-development',
        title: 'Describe the web page',
        question: "Which element is used to set the description for a web page?",
        options: [
            '\`img\`',
            '\`meta\`',
            '\`slot\`',
            '\`figure\`'
        ],
        random: true,
        answer: '\`meta\`',
    },
    {
        id: 21,
        type: 'radio',
        category: 'html',
        subcategory: 'intro-into-web-development',
        title: 'Open graph properties',
        question: "What are open graph properties used for?",
        options: [
            'embedding interactive multimedia content directly into web pages',
            'set how your website\'s content will be seen on different social media platforms',
            'generating dynamic pop-up advertisements on websites',
            'encrypting sensitive data transmitted between web servers and users\' browsers'
        ],
        random: true,
        answer: 'set how your website\'s content will be seen on different social media platforms',
    },
    {
        id: 22,
        type: 'radio',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'No audio',
        question: "What attribute allows the audio to start in a muted state?",
        options: [
            '\`mute\`',
            '\`quiet\`',
            '\`pause\`',
            '\`muted\`'
        ],
        random: true,
        answer: '\`muted\`',
    },
    {
        id: 23,
        type: 'radio',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'Play/pause',
        question: "Which attribute lets you see the play and pause buttons?",
        options: [
            '\`loop\`',
            '\`controls\`',
            '\`details\`',
            '\`muted\`',
            '\`buttons\`'
        ],
        random: true,
        answer: '\`controls\`',
    },
    {
        id: 24,
        type: 'radio',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'Don\'t do it',
        question: "Which file format should you never compress?",
        options: [
            'WEBP',
            'PNG',
            'JPG',
            'GIF'
        ],
        random: true,
        answer: 'JPG',
    },
    {
        id: 25,
        type: 'radio',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'Master raster',
        question: "What is a raster image?",
        options: [
            'an image which stores paths, lines, points, and curves',
            'an image which stores color data for each pixel',
            'all images are raster images',
            'an image which is easily scalable'
        ],
        random: true,
        answer: 'an image which stores color data for each pixel',
    },
    {
        id: 26,
        type: 'radio',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'How to vector',
        question: "What is a vector image?",
        options: [
            'an image which stores paths, lines, points, and curves',
            'an image which stores color data for each pixel',
            'all images are vector images',
            'an image which is not easily scalable'
        ],
        random: true,
        answer: 'an image which stores paths, lines, points, and curves',
    },
    {
        id: 27,
        type: 'radio',
        category: 'html',
        subcategory: 'visual-content-and-media',
        title: 'How to SVG',
        question: "How does an SVG store data?",
        options: [
            'as pixels',
            'as binary',
            'as hexadecimal',
            'as XML'
        ],
        random: true,
        answer: 'as XML',
    }
]