export default [
    {
        id: 1,
        type: 'radio',
        category: 'intro-to-comp',
        subcategory: 'how-comp-work',
        title: 'RAM',
        question: "What is RAM?",
        options: [
            'long term memory',
            'short term memory',
            'the main circuit board',
            'a video card',
        ],
        random: true,
        answer: 'short term memory',
    },
    {
        id: 2,
        type: 'radio',
        category: 'intro-to-comp',
        subcategory: 'how-comp-work',
        title: 'Network Card',
        question: "What is the network card responsible for?",
        options: [
            'rendering visuals on the computer screen',
            'playing sound on the computer speakers',
            'connecting the computer to the internet',
            'storing short term memory',
        ],
        random: true,
        answer: 'connecting the computer to the internet',
    },
    {
        id: 3,
        type: 'radio',
        category: 'intro-to-comp',
        subcategory: 'how-comp-work',
        title: 'Tie up loose ends',
        question: "What part of a computer is used to connect the other internal components together?",
        options: [
            'memory',
            'processor',
            'graphics card',
            'motherboard',
        ],
        random: true,
        answer: 'motherboard',
    },
    // {
    //     id: 1,
    //     type: 'radio',
    //     category: 'intro-to-comp',
    //     subcategory: '',
    //     title: '',
    //     question: "",
    //     options: [
    //         '',
    //         '',
    //         '',
    //         '',
    //     ],
    //     random: true,
    //     answer: '',
    // },
    // {
    //     id: 1,
    //     type: 'radio',
    //     category: 'intro-to-comp',
    //     subcategory: '',
    //     title: '',
    //     question: "",
    //     options: [
    //         '',
    //         '',
    //         '',
    //         '',
    //     ],
    //     random: true,
    //     answer: '',
    // },
    // {
    //     id: 1,
    //     type: 'radio',
    //     category: 'intro-to-comp',
    //     subcategory: '',
    //     title: '',
    //     question: "",
    //     options: [
    //         '',
    //         '',
    //         '',
    //         '',
    //     ],
    //     random: true,
    //     answer: '',
    // },
]