export default [
    // Intro to Java section
    {
        id: 1,
        type: 'radio',
        title: '',
        question: "What does the Java compiler \`javac\` produce?",
        options: [
            'machine code',
            'source code',
            'byte code',
            'HTML',
        ],
        answer: 'byte code',
    },
    {
        id: 2,
        type: 'radio',
        title: '',
        question: "What is the purpose of the Java Virtual Machine?",
        options: [
            'it is a debugger for Java programs',
            'to translate Java source code to byte code',
            'to execute Java byte code',
        ],
        answer: 'to execute Java byte code',
    },
    {
        id: 3,
        type: 'radio',
        title: '',
        question: "Which command is used to compile a Java program?",
        options: [
            '\`java\`',
            '\`javac\`',
            '\`compile\`',
            '\`run\`',
        ],
        answer: '\`javac\`',
    },
    {
        id: 4,
        type: 'radio',
        title: '',
        question: "What is byte code?",
        options: [
            'human-readable source code',
            'machine code for the CPU',
            'code that is executed by the JVM',
            'a type of error in Java',
        ],
        answer: 'code that is executed by the JVM',
        description: '**Byte code** is an intermediate code generated by compilers that can be executed by the JVM'
    },
    {
        id: 5,
        type: 'radio',
        title: '',
        question: "What is the JVM?",
        options: [
            'a text editor for writing Java programs',
            'a compiler that translates Java source code to byte code',
            'a virtual machine that executes Java byte code',
            'a library for Java graphics',
        ],
        answer: 'a virtual machine that executes Java byte code',
    },
    {
        id: 6,
        type: 'radio',
        title: '',
        question: "What does the Java compiler generate?",
        options: [
            'source code',
            'byte code',
            'machine code',
        ],
        answer: 'byte code',
    },
    {
        id: 7,
        type: 'radio',
        title: '',
        question: "In Java, what is a source file?",
        options: [
            'a file containing machine code',
            'a file containing Java programming statements',
            'a file containing byte code',
        ],
        answer: 'a file containing Java programming statements',
        description: 'A **source file** is a file containing Java programming statements, saved with a \`.java\` extension.'
    },
    {
        id: 8,
        type: 'radio',
        title: '',
        question: "What is a compiler?",
        options: [
            'a program that translates source code into machine code',
            'a program that translates source code into byte code',
            'a program that executes byte code',
            'a program that manages memory',
        ],
        answer: 'a program that translates source code into byte code',
    },
    {
        id: 9,
        type: 'radio',
        title: '',
        question: "What is the difference between machine language code and byte code?",
        options: [
            'machine language code is executed directly by the CPU, while byte code is executed by the Java Virtual Machine',
            'byte code is human-readable, while machine language code is not',
            'byte code is used exclusively in Java, while machine language code is used by (most) other programming languages',
            'there is no difference, they are synonyms',
        ],
        answer: 'machine language code is executed directly by the CPU, while byte code is executed by the Java Virtual Machine'
    },
]